<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
	<PackageId>JosephPKC.IO.FileIOWrapper</PackageId>
	<Version>1.0.1</Version>
	<Authors>JosephPKC</Authors>
	<Company>JosephPKC</Company>
	<IsPackable>true</IsPackable>
	<Title>JosephPKC.FileIOWrapper</Title>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
	<None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y /d &quot;$(ProjectDir)obj\Release\net9.0\$(ProjectName).dll&quot; &quot;..\..\..\bin\&quot;" />
  </Target>

</Project>
