<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

	    <PackageId>JosephPKC.Db.SqliteDbWrapper</PackageId>
	    <Version>1.0.2</Version>
	    <Authors>JosephPKC</Authors>
	    <Company>JosephPKC</Company>
	    <IsPackable>true</IsPackable>
	    <Title>JosephPKC.SqliteDbWrapper</Title>
	    <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
	    <None Include="README.md" Pack="true" PackagePath="\"/>
        <PackageReference Include="JosephPKC.Logs.LogWrapper" Version="1.3.0" />
        <PackageReference Include="JosephPKC.Store.Cache" Version="1.0.0" />
        <PackageReference Include="JosephPKC.Utils.ExceptionExts" Version="1.0.0" />
        <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
        <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
        <PackageReference Include="System.Drawing.Common" Version="4.7.2" />
    </ItemGroup>

</Project>
