<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
	<PackageId>JosephPKC.PkmApi.TestDtos</PackageId>
	<Version>1.0.0</Version>
	<Authors>JosephPKC</Authors>
	<Company>JosephPKC</Company>
	<IsPackable>true</IsPackable>
	<Title>PkmApi.TestDtos</Title>
	<Description>A simple library that provides test DTOs.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PkmApi\PkmApi.csproj" />
  </ItemGroup>

</Project>
