<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>JosephPKC.Logs.LogWrapper</PackageId>
		<Version>1.2.0</Version>
		<Authors>JosephPKC</Authors>
		<Company>JosephPKC</Company>
		<IsPackable>true</IsPackable>
		<Title>JosephPKC.LogWrapper</Title>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<PackageReference Include="log4net" Version="3.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
	</ItemGroup>

</Project>