<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<PackageId>JosephPKC.Api.PkmApi</PackageId>
	<Version>1.5.2</Version>
	<Authors>JosephPKC</Authors>
	<Company>JosephPKC</Company>
	<IsPackable>true</IsPackable>
	<Title>JosephPKC.PkmApi</Title>
	<Description>A simple wrapper library for PokeApi used for personal projects. Not meant for business/commercial use.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JosephPKC.IO.ApiGetter" Version="1.0.0" />
    <PackageReference Include="JosephPKC.IO.JsonParser" Version="1.0.1" />
    <PackageReference Include="JosephPKC.Logs.LogWrapper" Version="1.3.0" />
    <PackageReference Include="JosephPKC.Store.Cache" Version="1.0.1" />
    <PackageReference Include="JosephPKC.Utils.UriUtils" Version="1.0.0" />
  </ItemGroup>

</Project>
