name: NuGet Db.LiteDbWrapper
run-name: Build for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  push:
    branches:
      - main
    paths: 
      - 'Db/LiteDbWrapper/**'

jobs:
  deploy-nuget:
    uses: ./.github/workflows/rw-nuget.yaml
    with:
      pckg-name: JosephPKC.Db.LiteDbWrapper
      sln-path: ./Db/LiteDbWrapper/LiteDbWrapper.sln
      proj-path: ./Db/LiteDbWrapper/LiteDbWrapper/LiteDbWrapper.csproj
    secrets: inherit
