name: SonarQube Db.LiteDbWrapper
run-name: Run SonarQube analysis for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - 'Db/LiteDbWrapper/**'
  
jobs:
  sonar-qube-analysis:
    uses: ./.github/workflows/rw-sonar-cover.yaml
    with:
      sln-file-path: ./Db/LiteDbWrapper/LiteDbWrapper.sln
      test-dll-file-path: ./Db/LiteDbWrapper/LiteDbWrapper.Test/bin/Release/net9.0/LiteDbWrapper.Test.dll
    secrets: inherit