name: SonarQube Db.SqliteDbWrapper
run-name: Run SonarQube analysis for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - 'Db/SQLiteDbWrapper/**'
  
jobs:
  sonar-qube-analysis:
    uses: ./.github/workflows/rw-sonar-cover.yaml
    with:
      sln-file-path: ./Db/SQLiteDbWrapper/SQLiteDbWrapper.sln
      test-dll-file-path: ./Db/SQLiteDbWrapper/SQLiteDbWrapper.Test/bin/Debug/net9.0/SqliteDbWrapper.Test.dll
    secrets: inherit