name: SonarQube IO.FileIOWrapper
run-name: Run SonarQube analysis for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - 'IO/FileIOWrapper/**'
  
jobs:
  sonar-qube-analysis:
    uses: ./.github/workflows/rw-sonar.yaml
    with:
      sln-file-path: ./IO/FileIOWrapper/FileIOWrapper.sln
      test-dll-file-path: ./IO/FileIOWrapper/FileIOWrapper.Test/bin/Debug/net9.0/FileIOWrapper.Test.dll
    secrets: inherit