name: SonarQube IO.JsonParser
run-name: Run SonarQube analysis for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - 'IO/JsonParser/**'
  
jobs:
  sonar-qube-analysis:
    uses: ./.github/workflows/rw-sonar-cover.yaml
    with:
      sln-file-path: ./IO/JsonParser/JsonParser.sln
      test-dll-file-path: ./IO/JsonParser/JsonParser.Test/bin/Release/net9.0/JsonParser.Test.dll
    secrets: inherit