name: NuGet Store.RedisCache
run-name: Build for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  push:
    branches:
      - main
    paths: 
      - 'Store/RedisCache/**'

jobs:
  deploy-nuget:
    uses: ./.github/workflows/rw-nuget.yaml
    with:
      pckg-name: JosephPKC.Store.RedisCache
      sln-path: ./Store/RedisCache/RedisCache.sln
      proj-path: ./Store/RedisCache/RedisCache/RedisCache.csproj
    secrets: inherit
