name: SonarQube Store.Cache
run-name: Run SonarQube analysis for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - 'Store/Cache/**'
  
jobs:
  sonar-qube-analysis:
    uses: ./.github/workflows/rw-sonar.yaml
    with:
      sln-file-path: ./Store/Cache/Cache.sln
    secrets: inherit