name: SonarQube Utils.ExceptionExts
run-name: Run SonarQube analysis for PR ( ${{ github.event.number }} ${{ github.event.pull_request.title }}) by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - 'Utils/ExceptionExts/**'
  
jobs:
  sonar-qube-analysis:
    uses: ./.github/workflows/rw-sonar.yaml
    with:
      sln-file-path: ./Utils/ExceptionExts/ExceptionExts.sln
      test-dll-file-path: ./Utils/ExceptionExts/ExceptionExts.Test/bin/Debug/net9.0/ExceptionExts.Test.dll
    secrets: inherit